export const sampleFormSchema = {
  title: "Job Application Form",
  submitButtonText: "Submit Application",
  fields: [
    {
      type: "text",
      name: "fullName",
      label: "Full Name",
      placeholder: "Enter your full name",
      required: true,
      pattern: "^[A-Za-z ]{3,50}$",
      patternMessage:
        "Name must be 3-50 characters and contain only letters and spaces",
    },
    {
      type: "email",
      name: "email",
      label: "Email Address",
      placeholder: "your.email@example.com",
      required: true,
      helpText: "We'll never share your email with anyone else.",
    },
    {
      type: "text",
      name: "phone",
      label: "Phone Number",
      placeholder: "(123) 456-7890",
      pattern: "^[0-9()-+ ]{10,15}$",
      patternMessage: "Please enter a valid phone number",
    },
    {
      type: "section",
      name: "education",
      label: "Education",
      description: "Please provide your educational background",
      fields: [
        {
          type: "text",
          name: "university",
          label: "University/College",
          placeholder: "Enter university name",
          required: true,
        },
        {
          type: "text",
          name: "degree",
          label: "Degree",
          placeholder: "e.g., Bachelor of Science",
        },
        {
          type: "text",
          name: "major",
          label: "Major",
          placeholder: "e.g., Computer Science",
        },
        {
          type: "select",
          name: "graduationYear",
          label: "Graduation Year",
          options: [
            { value: "", label: "Select Year" },
            { value: "2023", label: "2023" },
            { value: "2022", label: "2022" },
            { value: "2021", label: "2021" },
            { value: "2020", label: "2020" },
            { value: "2019", label: "2019" },
            { value: "2018", label: "2018" },
            { value: "other", label: "Other" },
          ],
        },
        {
          type: "date",
          name: "graduationDate",
          label: "Graduation Date",
          helpText: "Select the exact date of graduation if known",
        },
      ],
    },
    {
      type: "section",
      name: "experience",
      label: "Work Experience",
      fields: [
        {
          type: "text",
          name: "company",
          label: "Company Name",
          placeholder: "Enter company name",
        },
        {
          type: "text",
          name: "position",
          label: "Position",
          placeholder: "e.g., Software Engineer",
        },
        {
          type: "textarea",
          name: "responsibilities",
          label: "Responsibilities",
          placeholder: "Describe your key responsibilities",
          rows: 3,
        },
        {
          type: "section",
          name: "duration",
          label: "Employment Duration",
          fields: [
            {
              type: "text",
              name: "startDate",
              label: "Start Date",
              placeholder: "MM/YYYY",
            },
            {
              type: "text",
              name: "endDate",
              label: "End Date",
              placeholder: "MM/YYYY or Present",
            },
          ],
        },
      ],
    },
    {
      type: "section",
      name: "skills",
      label: "Skills",
      fields: [
        {
          type: "checkbox",
          name: "javascript",
          label: "JavaScript",
          checkboxLabel: "JavaScript",
        },
        {
          type: "checkbox",
          name: "react",
          label: "React",
          checkboxLabel: "React",
        },
        {
          type: "checkbox",
          name: "node",
          label: "Node.js",
          checkboxLabel: "Node.js",
        },
        {
          type: "checkbox",
          name: "python",
          label: "Python",
          checkboxLabel: "Python",
        },
        {
          type: "checkbox",
          name: "java",
          label: "Java",
          checkboxLabel: "Java",
        },
        {
          type: "checkbox",
          name: "csharp",
          label: "C#",
          checkboxLabel: "C#",
        },
      ],
    },
    {
      type: "radio",
      name: "availability",
      label: "Availability",
      options: [
        { value: "fullTime", label: "Full-time" },
        { value: "partTime", label: "Part-time" },
        { value: "contract", label: "Contract" },
        { value: "freelance", label: "Freelance" },
      ],
      required: true,
    },
    {
      type: "number",
      name: "expectedSalary",
      label: "Expected Salary (USD)",
      min: 0,
      max: 500000,
      helpText: "Enter your expected annual salary",
    },
    {
      type: "file",
      name: "resume",
      label: "Resume",
      accept: ".pdf,.doc,.docx",
      helpText: "Upload your resume (PDF, DOC, or DOCX)",
    },
    {
      type: "textarea",
      name: "coverLetter",
      label: "Cover Letter",
      placeholder: "Tell us why you're a good fit for this position",
      rows: 5,
    },
    {
      type: "checkbox",
      name: "termsAgreed",
      label: "Terms and Conditions",
      checkboxLabel: "I agree to the terms and conditions",
      required: true,
    },
  ],
};
